---
- name: Create groups
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name }}"
    system: "{{ item.system|default('no') }}"
    state: present
  with_items: "{{ users_groups }}"
  when: "item.not_on_hosts is not defined or inventory_hostname not in item.not_on_hosts"
