---
- name: Delete groups in absent
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name|default('') }}"
    system: "{{ item.system|default('no') }}"
    state: absent
  with_items: "{{ users_absent_groups }}"
  when: ((only_on_hosts is not defined and not_on_hosts is not defined) or (only_on_hosts is defined and not_on_hosts is defined)) or (only_on_hosts is defined and inventory_hostname in only_on_hosts) or (not_on_hosts is defined and inventory_hostname not in not_on_hosts)
