---
- name: Create groups
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name }}"
    system: "{{ item.system|default('no') }}"
    state: present
  with_items: "{{ users_groups }}"
  when: ((only_on_hosts is not defined and not_on_hosts is not defined) or (only_on_hosts is defined and not_on_hosts is defined)) or (only_on_hosts is defined and inventory_hostname in only_on_hosts) or (not_on_hosts is defined and inventory_hostname not in not_on_hosts)
