---
- name: Delete groups
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ users_groups }}"
  when: |
    item.state | default ('present') == 'absent'
