---
- name: Create and delete groups
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name }}"
    system: "{{ item.system|default('no') }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ users_groups }}"
