---
- name: Create groups
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name }}"
    system: "{{ item.system|default('no') }}"
    state: "{{ item.state }}"
  with_items: "{{ users_groups }}"
  when: item.state == 'present'
