---
- ansible.builtin.include_tasks:
    file: groups_create.yml

- ansible.builtin.include_tasks:
    file: users.yml

- ansible.builtin.include_tasks:
    file: sudo.yml

- ansible.builtin.include_tasks:
    file: groups_delete.yml

- ansible.builtin.include_tasks:
    file: umask.yml
  when: users_umask_set
