---
- name: Stat /etc/sudoers
  stat:
    path: /etc/sudoers
  register: sudoers
  with_items: "{{ users }}"
  when: (item.only_on_hosts is not defined and item.not_on_hosts is not defined) or (item.only_on_hosts is defined and item.not_on_hosts is defined) or (item.only_on_hosts is defined and inventory_hostname in item.only_on_hosts) or (item.not_on_hosts is defined and inventory_hostname not in item.not_on_hosts)

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak
  when: sudoers is defined and sudoers

- name: Copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp
  register: sudoers_tmp
  when: sudoers is defined and sudoers

- name: Add sudo users
  lineinfile:
    dest: /etc/sudoers.tmp
    state: present
    regexp: '^{{ item.name }}'
    line: "{{ item.name }} ALL=(ALL) {{ item.mode|default('ALL')}}"
    validate: "visudo -q -c -f %s"
  when: (item.only_on_hosts is not defined and item.not_on_hosts is not defined) or (item.only_on_hosts is defined and item.not_on_hosts is defined) or (item.only_on_hosts is defined and inventory_hostname in item.only_on_hosts) or (item.not_on_hosts is defined and inventory_hostname not in item.not_on_hosts) and sudoers_tmp.rc is defined and sudoers_tmp.rc == 0
  with_items: "{{ users_sudo }}"

- name: Remove absent sudo users
  lineinfile:
    dest: /etc/sudoers.tmp
    state: absent
    regexp: '^{{ item.name }}'
    validate: "visudo -q -c -f %s"
  when: (item.only_on_hosts is not defined and item.not_on_hosts is not defined) or (item.only_on_hosts is defined and item.not_on_hosts is defined) or (item.only_on_hosts is defined and inventory_hostname in item.only_on_hosts) or (item.not_on_hosts is defined and inventory_hostname not in item.not_on_hosts) and sudoers_tmp.rc is defined and sudoers_tmp.rc == 0
  with_items: "{{ users_absent_sudo }}"

- name: Make sure ssh-agent works via sudo
  lineinfile:
    dest: /etc/sudoers.tmp
    state: present
    regexp: '^Defaults env_keep\+\=SSH_AUTH_SOCK'
    line: 'Defaults env_keep+=SSH_AUTH_SOCK'
    validate: "visudo -q -c -f %s"
  when: sudoers_tmp.rc is defined and sudoers_tmp.rc == 0

- name: Copy sudoers file back
  shell: cp -f /etc/sudoers.tmp /etc/sudoers
  when: sudoers_tmp.rc is defined and sudoers_tmp.rc == 0
