---
- name: Install sudo
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: sudo
    state: latest

- name: Stat /etc/sudoers
  stat:
    path: "{{ sudoers_file }}"
  register: stat_sudoers

- name: Fail when the sudoers return code is not defined
  fail:
    msg: "Error stating sudoers file: {{ sudoers_file }}"
  when: not stat_sudoers.stat.exists

- name: Add/Remove sudo users
  lineinfile:
    dest: "{{ sudoers_file }}"
    state: "{{ item.state|default('present') }}"
    regexp: '^{{ item.name }}.*$'
    line: "{{ item.name }} ALL=(ALL) {{ item.mode|default('ALL')}}"
    validate: "visudo -q -c -f %s"
  with_items: "{{ users_sudo }}"

- name: Make sure ssh-agent works via sudo
  lineinfile:
    dest: "{{ sudoers_file }}"
    state: present
    regexp: '^Defaults env_keep\+\=SSH_AUTH_SOCK'
    line: 'Defaults env_keep+=SSH_AUTH_SOCK'
    validate: "visudo -q -c -f %s"
