---
- name: Stat /etc/sudoers
  stat:
    path: "{{ sudoers_file }}"
  register: stat_sudoers
  with_items: "{{ users }}"

- name: Fail when the sudoers return code is not defined
  fail:
    msg: "Error stating sudoers file: {{ sudoers_file }}"
  when: stat_sudoers.stat is not defined

- name: Create temporary sudoers file
  command: "cp -f {{ sudoers_file }} /etc/sudoers-tmp-ansible"
  when: stat_sudoers.stat.exists

- name: Remove absent sudo users
  lineinfile:
    dest: /tmp/sudoers-ansible-bak.tmp
    state: absent
    regexp: '^{{ item.name }}'
    validate: "visudo -q -c -f %s"
  with_items: "{{ users_sudo }}"

- name: Add sudo users
  lineinfile:
    dest: /tmp/sudoers-ansible-bak.tmp
    state: present
    regexp: '^{{ item.name }}'
    line: "{{ item.name }} ALL=(ALL) {{ item.mode|default('ALL')}}"
    validate: "visudo -q -c -f %s"
  with_items: "{{ users }}"
  when: item.sudo is defined

- name: Make sure ssh-agent works via sudo
  lineinfile:
    dest: /tmp/sudoers-ansible-bak.tmp
    state: present
    regexp: '^Defaults env_keep\+\=SSH_AUTH_SOCK'
    line: 'Defaults env_keep+=SSH_AUTH_SOCK'
    validate: "visudo -q -c -f %s"

- name: Copy sudoers file back
  command: cp -f /tmp/sudoers-ansible-bak.tmp /etc/sudoers

- name: Remove temporary sudoers backup file
  file:
    path: /tmp/sudoers-ansible-bak.tmp
    state: absent
