---
- name: Create users
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment|default('') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group|default('users') }}"
    non_unique: "{{ item.non_unique|default('no') }}"
    system: "{{ item.system|default('no') }}"
    groups: "{% if item.groups is defined %}{% for group in item.groups %}{% if inventory_hostname == group.host %}{{ group.name }}{% if not loop.last %},{% endif %}{% endif %}{% endfor %}{% endif %}"
    move_home: "{{ item.system|default('no') }}"
    home: "{{ item.home }}"
    createhome: "{{ item.createhome|default('yes') }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
  with_items: "{{ users }}"
  when: (item.only_on_hosts is not defined and item.not_on_hosts is not defined) or (item.only_on_hosts is defined and item.not_on_hosts is defined) or (item.only_on_hosts is defined and inventory_hostname in item.only_on_hosts) or (item.not_on_hosts is defined and inventory_hostname not in item.not_on_hosts)
