---
- name: Remove absent users
  user:
    name: "{{ item.name }}"
    state: absent
    comment: "{{ item.comment|default('') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
  with_items: "{{ users_absent }}"
  when: ((only_on_hosts is not defined and not_on_hosts is not defined) or (only_on_hosts is defined and not_on_hosts is defined)) or (only_on_hosts is defined and inventory_hostname in only_on_hosts) or (not_on_hosts is defined and inventory_hostname not in not_on_hosts)
