---
- name: Remove absent users
  user:
    name: "{{ item.name }}"
    state: absent
    comment: "{{ item.comment|default('') }}"
    uid: "{{ item.uid }}"
  with_items: "{{ users }}"
  when: item.state|default('present') != "present"

- name: Debug
  debug:
    var: users

- name: Create users
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment|default('') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group|default('users') }}"
    non_unique: "{{ item.non_unique|default('no') }}"
    system: "{{ item.system|default('no') }}"
    groups: "{% if item.groups is defined %}{% for group in item.groups %}{{ group }}{% endfor %}{% endif %}"
    move_home: "{{ item.system|default('no') }}"
    home: "{{ item.home }}"
    createhome: "{{ item.createhome|default('yes') }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
  with_items: "{{ users }}"
  when: item.state|default('present') != "absent"
