---
- name: Remove absent users
  user:
    name: "{{ item.name }}"
    state: absent
    comment: "{{ item.comment|default('') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
  with_items: "{{ users_absent }}"
  when: "item.not_on_hosts is not defined or inventory_hostname not in item.not_on_hosts"
